-- ==============================================================================
-- COMPLAINTS & REQUESTS PORTAL - COMPLETE ORACLE SCHEMA
-- ==============================================================================

-- 1. MASTER TABLES
CREATE TABLE MST_DIVISION (
    DIVISION_ID NUMBER PRIMARY KEY,
    DIVISION_CODE VARCHAR2(50) NOT NULL,
    DIVISION_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

CREATE TABLE MST_ROLE (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_CODE VARCHAR2(50) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    ROLE_CATEGORY VARCHAR2(50),
    REQUIRES_DIVISION CHAR(1) DEFAULT 'N',
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

CREATE TABLE MST_SERVICE (
    SERVICE_ID NUMBER PRIMARY KEY,
    SERVICE_CODE VARCHAR2(50) NOT NULL,
    SERVICE_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

CREATE TABLE MST_REQUEST_TYPE (
    REQUEST_TYPE_ID NUMBER PRIMARY KEY,
    SERVICE_ID NUMBER REFERENCES MST_SERVICE(SERVICE_ID),
    TYPE_CODE VARCHAR2(50) NOT NULL,
    TYPE_NAME VARCHAR2(100) NOT NULL,
    IS_FLOW_BASED CHAR(1) DEFAULT 'N',
    SLA_HOURS NUMBER,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

CREATE TABLE MST_REQUEST_SUBTYPE (
    SUBTYPE_ID NUMBER PRIMARY KEY,
    REQUEST_TYPE_ID NUMBER REFERENCES MST_REQUEST_TYPE(REQUEST_TYPE_ID),
    SUBTYPE_CODE VARCHAR2(50) NOT NULL,
    SUBTYPE_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

CREATE TABLE MST_FIELD_DEFINITION (
    FIELD_ID NUMBER PRIMARY KEY,
    REQUEST_TYPE_ID NUMBER REFERENCES MST_REQUEST_TYPE(REQUEST_TYPE_ID),
    SUBTYPE_ID NUMBER REFERENCES MST_REQUEST_SUBTYPE(SUBTYPE_ID),
    FIELD_CODE VARCHAR2(50) NOT NULL,
    FIELD_LABEL VARCHAR2(100) NOT NULL,
    FIELD_TYPE VARCHAR2(50) NOT NULL,
    IS_MANDATORY CHAR(1) DEFAULT 'N',
    DISPLAY_ORDER NUMBER DEFAULT 0,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

-- 2. WORKFLOW ENGINE TABLES
CREATE TABLE MST_WORKFLOW (
    WORKFLOW_ID NUMBER PRIMARY KEY,
    REQUEST_TYPE_ID NUMBER REFERENCES MST_REQUEST_TYPE(REQUEST_TYPE_ID),
    WORKFLOW_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE MST_WORKFLOW_STAGE (
    STAGE_ID NUMBER PRIMARY KEY,
    WORKFLOW_ID NUMBER REFERENCES MST_WORKFLOW(WORKFLOW_ID),
    STAGE_SEQUENCE NUMBER NOT NULL,
    STAGE_NAME VARCHAR2(100) NOT NULL,
    APPROVER_ROLE_ID NUMBER REFERENCES MST_ROLE(ROLE_ID),
    ASSIGNMENT_MODE VARCHAR2(50) DEFAULT 'SPECIFIC_PERSON',
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

CREATE TABLE TRN_WORKFLOW_ROUTING (
    ROUTING_ID NUMBER PRIMARY KEY,
    STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID),
    ACTION_TYPE VARCHAR2(50) NOT NULL,
    NEXT_STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID)
);

-- 3. USER MANAGEMENT TABLES
CREATE TABLE TRN_USER_ROLE (
    USER_ROLE_ID NUMBER PRIMARY KEY,
    PCNO VARCHAR2(50) NOT NULL,
    ROLE_ID NUMBER REFERENCES MST_ROLE(ROLE_ID),
    DIVISION_ID NUMBER REFERENCES MST_DIVISION(DIVISION_ID),
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE TRN_STANDBY_ASSIGNMENT (
    ASSIGNMENT_ID NUMBER PRIMARY KEY,
    ORIGINAL_USER_ROLE_ID NUMBER REFERENCES TRN_USER_ROLE(USER_ROLE_ID),
    STANDBY_PCNO VARCHAR2(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE TRN_TECH_EXPERT_SERVICE (
    MAPPING_ID NUMBER PRIMARY KEY,
    PCNO VARCHAR2(50) NOT NULL,
    SERVICE_ID NUMBER REFERENCES MST_SERVICE(SERVICE_ID),
    REQUEST_TYPE_ID NUMBER REFERENCES MST_REQUEST_TYPE(REQUEST_TYPE_ID),
    ASSIGNED_BY VARCHAR2(50),
    ASSIGNED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
);

-- 4. TRANSACTION / TICKET TABLES
CREATE SEQUENCE SEQ_REQUEST START WITH 1 INCREMENT BY 1;

CREATE TABLE TRN_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    REQUEST_NUMBER VARCHAR2(50) UNIQUE NOT NULL,
    REQUEST_TYPE_ID NUMBER REFERENCES MST_REQUEST_TYPE(REQUEST_TYPE_ID),
    SUBTYPE_ID NUMBER REFERENCES MST_REQUEST_SUBTYPE(SUBTYPE_ID),
    WORKFLOW_ID NUMBER REFERENCES MST_WORKFLOW(WORKFLOW_ID),
    REQUESTER_PCNO VARCHAR2(50) NOT NULL,
    DIVISION_ID NUMBER REFERENCES MST_DIVISION(DIVISION_ID),
    CURRENT_STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID),
    STATUS VARCHAR2(50) NOT NULL,
    PICKED_BY_PCNO VARCHAR2(50),
    PICKED_DATE TIMESTAMP,
    REJECTION_COUNT NUMBER DEFAULT 0,
    SUBMITTED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CLOSED_DATE TIMESTAMP,
    SLA_DUE_DATE TIMESTAMP,
    -- Phase 1 Basic Details --
    ROOM_NO VARCHAR2(50),
    BUILDING VARCHAR2(100),
    FLOOR VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    RESOLUTION_REMARKS VARCHAR2(1000)
);

CREATE TABLE TRN_REQUEST_FIELD_VALUE (
    VALUE_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER REFERENCES TRN_REQUEST(REQUEST_ID),
    FIELD_ID NUMBER REFERENCES MST_FIELD_DEFINITION(FIELD_ID),
    VALUE_TEXT VARCHAR2(2000),
    VALUE_NUMBER NUMBER,
    VALUE_DATE DATE
);

CREATE TABLE TRN_REQUEST_STAGE_HISTORY (
    HISTORY_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER REFERENCES TRN_REQUEST(REQUEST_ID),
    STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID),
    ACTION_BY_PCNO VARCHAR2(50) NOT NULL,
    ACTED_AS_STANDBY CHAR(1) DEFAULT 'N',
    ACTION VARCHAR2(50) NOT NULL,
    REMARKS VARCHAR2(1000),
    ACTION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE TRN_REQUEST_ATTACHMENT (
    ATTACHMENT_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER REFERENCES TRN_REQUEST(REQUEST_ID),
    STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID),
    UPLOADED_BY_PCNO VARCHAR2(50) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    UPLOADED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 5. UTILITY TABLES
CREATE TABLE TRN_PORTAL_CONNECTION (
    CONN_ID NUMBER PRIMARY KEY,
    PCNO VARCHAR2(50) NOT NULL,
    CONNECTION_TYPE VARCHAR2(50),
    IP_ADDRESS VARCHAR2(50),
    MAC_ADDRESS VARCHAR2(50),
    PORT_NO VARCHAR2(50),
    SWITCH_NAME VARCHAR2(100),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP
);

CREATE TABLE TRN_EMAIL_QUEUE (
    EMAIL_ID NUMBER PRIMARY KEY,
    RECIPIENT_EMAIL VARCHAR2(200) NOT NULL,
    SUBJECT VARCHAR2(500) NOT NULL,
    BODY CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SENT_DATE TIMESTAMP,
    ERROR_MESSAGE VARCHAR2(1000)
);

CREATE TABLE TRN_AUDIT_LOG (
    AUDIT_ID NUMBER PRIMARY KEY,
    PCNO VARCHAR2(50),
    MODULE_NAME VARCHAR2(100),
    ENTITY_ID VARCHAR2(50),
    ACTION_TYPE VARCHAR2(50),
    ACTION_DESC VARCHAR2(1000),
    IP_ADDRESS VARCHAR2(50),
    ACTION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 6. DUMMY HR DATA (If you do not already have an hrdata.empdetails table)
-- NOTE: If your database already has hrdata.empdetails, DO NOT RUN THIS BLOCK.
/*
CREATE USER hrdata IDENTIFIED BY password;
GRANT CONNECT, RESOURCE TO hrdata;
CREATE TABLE hrdata.empdetails (
    PCNO VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100),
    DESIGNATION VARCHAR2(100),
    DIVNAME VARCHAR2(100),
    EMAIL VARCHAR2(100)
);
INSERT INTO hrdata.empdetails (PCNO, NAME, DESIGNATION, DIVNAME, EMAIL) VALUES ('123456', 'John Doe', 'Engineer', 'IT Services', 'john.doe@example.com');
COMMIT;
*/
