-- ==============================================================================
-- COMPLAINTS & REQUESTS PORTAL - UPDATE EXISTING SCHEMA
-- Run this script if you ALREADY have the base tables created!
-- ==============================================================================

-- 1. ADD NEW COLUMNS TO EXISTING TABLES
-- (Using a safe PL/SQL block so it won't fail if you run it twice)

BEGIN
   -- Add SLA_HOURS to MST_REQUEST_TYPE
   EXECUTE IMMEDIATE 'ALTER TABLE MST_REQUEST_TYPE ADD SLA_HOURS NUMBER';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
   -- Add Phase 1 basic fields to TRN_REQUEST
   EXECUTE IMMEDIATE 'ALTER TABLE TRN_REQUEST ADD SLA_DUE_DATE TIMESTAMP';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE TRN_REQUEST ADD ROOM_NO VARCHAR2(50)';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE TRN_REQUEST ADD BUILDING VARCHAR2(100)';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE TRN_REQUEST ADD FLOOR VARCHAR2(50)';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE TRN_REQUEST ADD DESCRIPTION VARCHAR2(1000)';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE TRN_REQUEST ADD RESOLUTION_REMARKS VARCHAR2(1000)';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- 2. CREATE ENTIRELY NEW TABLES
-- (These are the powerful features we built during development)

-- Workflow Engine
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE MST_WORKFLOW (
       WORKFLOW_ID NUMBER PRIMARY KEY,
       REQUEST_TYPE_ID NUMBER REFERENCES MST_REQUEST_TYPE(REQUEST_TYPE_ID),
       WORKFLOW_NAME VARCHAR2(100) NOT NULL,
       IS_ACTIVE CHAR(1) DEFAULT ''Y'',
       CREATED_BY VARCHAR2(50),
       CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
   )';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE MST_WORKFLOW_STAGE (
       STAGE_ID NUMBER PRIMARY KEY,
       WORKFLOW_ID NUMBER REFERENCES MST_WORKFLOW(WORKFLOW_ID),
       STAGE_SEQUENCE NUMBER NOT NULL,
       STAGE_NAME VARCHAR2(100) NOT NULL,
       APPROVER_ROLE_ID NUMBER REFERENCES MST_ROLE(ROLE_ID),
       ASSIGNMENT_MODE VARCHAR2(50) DEFAULT ''SPECIFIC_PERSON'',
       IS_ACTIVE CHAR(1) DEFAULT ''Y''
   )';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE TRN_WORKFLOW_ROUTING (
       ROUTING_ID NUMBER PRIMARY KEY,
       STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID),
       ACTION_TYPE VARCHAR2(50) NOT NULL,
       NEXT_STAGE_ID NUMBER REFERENCES MST_WORKFLOW_STAGE(STAGE_ID)
   )';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Standby/Vacation Rules
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE TRN_STANDBY_ASSIGNMENT (
       ASSIGNMENT_ID NUMBER PRIMARY KEY,
       ORIGINAL_USER_ROLE_ID NUMBER REFERENCES TRN_USER_ROLE(USER_ROLE_ID),
       STANDBY_PCNO VARCHAR2(50) NOT NULL,
       START_DATE DATE NOT NULL,
       END_DATE DATE NOT NULL,
       IS_ACTIVE CHAR(1) DEFAULT ''Y'',
       CREATED_BY VARCHAR2(50),
       CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
   )';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Tech Expert Connection Registry
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE TRN_PORTAL_CONNECTION (
       CONN_ID NUMBER PRIMARY KEY,
       PCNO VARCHAR2(50) NOT NULL,
       CONNECTION_TYPE VARCHAR2(50),
       IP_ADDRESS VARCHAR2(50),
       MAC_ADDRESS VARCHAR2(50),
       PORT_NO VARCHAR2(50),
       SWITCH_NAME VARCHAR2(100),
       STATUS VARCHAR2(20) DEFAULT ''ACTIVE'',
       CREATED_BY VARCHAR2(50),
       CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
       MODIFIED_BY VARCHAR2(50),
       MODIFIED_DATE TIMESTAMP
   )';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Background Email Queue
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE TRN_EMAIL_QUEUE (
       EMAIL_ID NUMBER PRIMARY KEY,
       RECIPIENT_EMAIL VARCHAR2(200) NOT NULL,
       SUBJECT VARCHAR2(500) NOT NULL,
       BODY CLOB,
       STATUS VARCHAR2(20) DEFAULT ''PENDING'',
       CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
       SENT_DATE TIMESTAMP,
       ERROR_MESSAGE VARCHAR2(1000)
   )';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
